FROM jenkins/jenkins:lts

ENV JENKINS_INSTALL_DIR  /DATA/jenkins
ENV JENKINS_HOME         /var/jenkins_home  
ARG gid=1000
ARG uid=1000

USER root

RUN mkdir -p $(dirname $JENKINS_HOME)  \
    && chown -R ${uid}:${gid} $JENKINS_HOME  \
    && chmod -R 755 $JENKINS_HOME 


EXPOSE 8080
EXPOSE 50000

WORKDIR $JENKINS_INSTALL_DIR
